grails-app/domain/com/app/translate/TranslationKey.groovy
package com.app.translate

import com.app.security.User

class TranslationKey {
    String key_id
    User updatedBy
    User createdBy
    static constraints = {
        key_id nullable:false, blank: false
        updatedBy nullable: true
        createdBy nullable: true
    }
    static mapping = {
        table("translation_key")
        key_id sqlType: 'nvarchar(max)'
    }

    String toString(){
        return key_id
    }
}

grails-app/controllers/com/app/translate/TranslationKeyController.groovy
package com.app.translate



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TranslationKeyController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond TranslationKey.list(params), model: [translationKeyInstanceCount: TranslationKey.count()]
    }

    def show(TranslationKey translationKeyInstance) {
        respond translationKeyInstance
    }

    def create() {
        respond new TranslationKey(params)
    }

    @Transactional
    def save(TranslationKey translationKeyInstance) {
        if (translationKeyInstance == null) {
            notFound()
            return
        }

        if (translationKeyInstance.hasErrors()) {
            respond translationKeyInstance.errors, view: 'create'
            return
        }

        translationKeyInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'translationKey.label', default: 'TranslationKey'), translationKeyInstance.id])
                redirect translationKeyInstance
            }
            '*' { respond translationKeyInstance, [status: CREATED] }
        }
    }

    def edit(TranslationKey translationKeyInstance) {
        respond translationKeyInstance
    }

    @Transactional
    def update(TranslationKey translationKeyInstance) {
        if (translationKeyInstance == null) {
            notFound()
            return
        }

        if (translationKeyInstance.hasErrors()) {
            respond translationKeyInstance.errors, view: 'edit'
            return
        }

        translationKeyInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'TranslationKey.label', default: 'TranslationKey'), translationKeyInstance.id])
                redirect translationKeyInstance
            }
            '*' { respond translationKeyInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(TranslationKey translationKeyInstance) {

        if (translationKeyInstance == null) {
            notFound()
            return
        }

        translationKeyInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'TranslationKey.label', default: 'TranslationKey'), translationKeyInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'translationKey.label', default: 'TranslationKey'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/translationKey/_form.gsp
<%@ page import="com.app.ef.translate.TranslationKey" %>



<div class="fieldcontain ${hasErrors(bean: translationKeyInstance, field: 'key_id', 'error')} required">
	<label for="key_id">
		<g:message code="translationKey.key_id.label" default="Keyid" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="key_id" required="" value="${translationKeyInstance?.key_id}"/>

</div>

grails-app/views/translationKey/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translationKey.label', default: 'TranslationKey')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-translationKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-translationKey" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${translationKeyInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${translationKeyInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:translationKeyInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/translationKey/edit.gsp
<%@ page import="com.app.ef.translate.TranslationKey" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translationKey.label', default: 'TranslationKey')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-translationKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-translationKey" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${translationKeyInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${translationKeyInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:translationKeyInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${translationKeyInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/translationKey/index.gsp
<%@ page import="com.app.ef.translate.TranslationKey" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translationKey.label', default: 'TranslationKey')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-translationKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-translationKey" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="key_id" title="${message(code: 'translationKey.key_id.label', default: 'Keyid')}" />
					
						<th><g:message code="translationKey.updatedBy.label" default="Updated By" /></th>
					
						<th><g:message code="translationKey.createdBy.label" default="Created By" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${translationKeyInstanceList}" status="i" var="translationKeyInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${translationKeyInstance.id}">${fieldValue(bean: translationKeyInstance, field: "key_id")}</g:link></td>
					
						<td>${fieldValue(bean: translationKeyInstance, field: "updatedBy")}</td>
					
						<td>${fieldValue(bean: translationKeyInstance, field: "createdBy")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${translationKeyInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/translationKey/show.gsp
<%@ page import="com.app.ef.translate.TranslationKey" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translationKey.label', default: 'TranslationKey')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-translationKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-translationKey" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list translationKey">
			
				<g:if test="${translationKeyInstance?.key_id}">
				<li class="fieldcontain">
					<span id="key_id-label" class="property-label"><g:message code="translationKey.key_id.label" default="Keyid" /></span>
					
						<span class="property-value" aria-labelledby="key_id-label"><g:fieldValue bean="${translationKeyInstance}" field="key_id"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${translationKeyInstance?.updatedBy}">
				<li class="fieldcontain">
					<span id="updatedBy-label" class="property-label"><g:message code="translationKey.updatedBy.label" default="Updated By" /></span>
					
						<span class="property-value" aria-labelledby="updatedBy-label"><g:link controller="user" action="show" id="${translationKeyInstance?.updatedBy?.id}">${translationKeyInstance?.updatedBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${translationKeyInstance?.createdBy}">
				<li class="fieldcontain">
					<span id="createdBy-label" class="property-label"><g:message code="translationKey.createdBy.label" default="Created By" /></span>
					
						<span class="property-value" aria-labelledby="createdBy-label"><g:link controller="user" action="show" id="${translationKeyInstance?.createdBy?.id}">${translationKeyInstance?.createdBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:translationKeyInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${translationKeyInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>