grails-app/domain/com/app/translate/Language.groovy
package com.app.translate

import com.app.security.User

class Language {
     String name
     String description
     String languageCode

    User updatedBy
    User createdBy
    static constraints = {
        name nullable: true, blank: true
        description nullable:  true , blank: true
        languageCode nullable: false, blank: false
        updatedBy nullable: true
        createdBy nullable: true
    }
    static mapping = {
        table("language")
        name sqlType: "nvarchar(max)"
        description sqlType: "nvarchar(max)"
        languageCode sqlType: "nvarchar(max)"
    }
    String toString(){
        return languageCode
    }
}

grails-app/controllers/com/app/translate/LanguageController.groovy
package com.app.translate



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class LanguageController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Language.list(params), model:[languageInstanceCount: Language.count()]
    }

    def show(Language languageInstance) {
        respond languageInstance
    }

    def create() {
        respond new Language(params)
    }

    @Transactional
    def save(Language languageInstance) {
        if (languageInstance == null) {
            notFound()
            return
        }

        if (languageInstance.hasErrors()) {
            respond languageInstance.errors, view:'create'
            return
        }

        languageInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'language.label', default: 'Language'), languageInstance.id])
                redirect languageInstance
            }
            '*' { respond languageInstance, [status: CREATED] }
        }
    }

    def edit(Language languageInstance) {
        respond languageInstance
    }

    @Transactional
    def update(Language languageInstance) {
        if (languageInstance == null) {
            notFound()
            return
        }

        if (languageInstance.hasErrors()) {
            respond languageInstance.errors, view:'edit'
            return
        }

        languageInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Language.label', default: 'Language'), languageInstance.id])
                redirect languageInstance
            }
            '*'{ respond languageInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Language languageInstance) {

        if (languageInstance == null) {
            notFound()
            return
        }

        languageInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Language.label', default: 'Language'), languageInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'language.label', default: 'Language'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/language/_form.gsp
<%@ page import="com.app.translate.Language" %>



<div class="fieldcontain ${hasErrors(bean: languageInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="language.name.label" default="Name" />
		
	</label>
	<g:textField name="name" value="${languageInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: languageInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="language.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${languageInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: languageInstance, field: 'languageCode', 'error')} required">
	<label for="languageCode">
		<g:message code="language.languageCode.label" default="Language Code" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="languageCode" required="" value="${languageInstance?.languageCode}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: languageInstance, field: 'updatedBy', 'error')} ">
	<label for="updatedBy">
		<g:message code="language.updatedBy.label" default="Updated By" />
		
	</label>
	<g:select id="updatedBy" name="updatedBy.id" from="${com.app.security.User.list()}" optionKey="id" value="${languageInstance?.updatedBy?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: languageInstance, field: 'createdBy', 'error')} ">
	<label for="createdBy">
		<g:message code="language.createdBy.label" default="Created By" />
		
	</label>
	<g:select id="createdBy" name="createdBy.id" from="${com.app.security.User.list()}" optionKey="id" value="${languageInstance?.createdBy?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

grails-app/views/language/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'language.label', default: 'Language')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-language" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-language" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${languageInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${languageInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:languageInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/language/edit.gsp
<%@ page import="com.app.translate.Language" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'language.label', default: 'Language')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-language" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-language" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${languageInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${languageInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:languageInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${languageInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/language/index.gsp
<%@ page import="com.app.translate.Language" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'language.label', default: 'Language')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-language" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-language" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'language.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'language.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="languageCode" title="${message(code: 'language.languageCode.label', default: 'Language Code')}" />
					
						<th><g:message code="language.updatedBy.label" default="Updated By" /></th>
					
						<th><g:message code="language.createdBy.label" default="Created By" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${languageInstanceList}" status="i" var="languageInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${languageInstance.id}">${fieldValue(bean: languageInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: languageInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: languageInstance, field: "languageCode")}</td>
					
						<td>${fieldValue(bean: languageInstance, field: "updatedBy")}</td>
					
						<td>${fieldValue(bean: languageInstance, field: "createdBy")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${languageInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/language/show.gsp
<%@ page import="com.app.translate.Language" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'language.label', default: 'Language')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-language" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-language" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list language">
			
				<g:if test="${languageInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="language.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${languageInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${languageInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="language.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${languageInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${languageInstance?.languageCode}">
				<li class="fieldcontain">
					<span id="languageCode-label" class="property-label"><g:message code="language.languageCode.label" default="Language Code" /></span>
					
						<span class="property-value" aria-labelledby="languageCode-label"><g:fieldValue bean="${languageInstance}" field="languageCode"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${languageInstance?.updatedBy}">
				<li class="fieldcontain">
					<span id="updatedBy-label" class="property-label"><g:message code="language.updatedBy.label" default="Updated By" /></span>
					
						<span class="property-value" aria-labelledby="updatedBy-label"><g:link controller="user" action="show" id="${languageInstance?.updatedBy?.id}">${languageInstance?.updatedBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${languageInstance?.createdBy}">
				<li class="fieldcontain">
					<span id="createdBy-label" class="property-label"><g:message code="language.createdBy.label" default="Created By" /></span>
					
						<span class="property-value" aria-labelledby="createdBy-label"><g:link controller="user" action="show" id="${languageInstance?.createdBy?.id}">${languageInstance?.createdBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:languageInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${languageInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>