grails-app/domain/com/app/translate/Translation.groovy
package com.app.translate

import com.app.security.User

class Translation {
    String text
    String translationKey
    Language language
    User updatedBy
    User createdBy
    static constraints = {
        text nullable: false, blank: false
        translationKey nullable: false, blank: false
        language nullable: false
        updatedBy nullable: true
        createdBy nullable: true
    }
    static mapping = {
        table("translation")
        text sqlType: 'nvarchar(max)'
    }
    String toString(){
        return text
    }
}

grails-app/controllers/com/app/translate/TranslationController.groovy
package com.app.translate



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TranslationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Translation.list(params), model:[translationInstanceCount: Translation.count()]
    }

    def show(Translation translationInstance) {
        respond translationInstance
    }

    def create() {
        respond new Translation(params)
    }

    @Transactional
    def save(Translation translationInstance) {
        if (translationInstance == null) {
            notFound()
            return
        }

        if (translationInstance.hasErrors()) {
            respond translationInstance.errors, view:'create'
            return
        }

        translationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'translation.label', default: 'Translation'), translationInstance.id])
                redirect translationInstance
            }
            '*' { respond translationInstance, [status: CREATED] }
        }
    }

    def edit(Translation translationInstance) {
        respond translationInstance
    }

    @Transactional
    def update(Translation translationInstance) {
        if (translationInstance == null) {
            notFound()
            return
        }

        if (translationInstance.hasErrors()) {
            respond translationInstance.errors, view:'edit'
            return
        }

        translationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Translation.label', default: 'Translation'), translationInstance.id])
                redirect translationInstance
            }
            '*'{ respond translationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Translation translationInstance) {

        if (translationInstance == null) {
            notFound()
            return
        }

        translationInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Translation.label', default: 'Translation'), translationInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'translation.label', default: 'Translation'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/translation/_form.gsp
<%@ page import="com.app.translate.Translation" %>



<div class="fieldcontain ${hasErrors(bean: translationInstance, field: 'text', 'error')} required">
	<label for="text">
		<g:message code="translation.text.label" default="Text" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="text" required="" value="${translationInstance?.text}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: translationInstance, field: 'translationKey', 'error')} required">
	<label for="translationKey">
		<g:message code="translation.translationKey.label" default="Translation Key" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="translationKey" required="" value="${translationInstance?.translationKey}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: translationInstance, field: 'language', 'error')} required">
	<label for="language">
		<g:message code="translation.language.label" default="Language" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="language" name="language.id" from="${com.app.translate.Language.list()}" optionKey="id" required="" value="${translationInstance?.language?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: translationInstance, field: 'updatedBy', 'error')} ">
	<label for="updatedBy">
		<g:message code="translation.updatedBy.label" default="Updated By" />
		
	</label>
	<g:select id="updatedBy" name="updatedBy.id" from="${com.app.security.User.list()}" optionKey="id" value="${translationInstance?.updatedBy?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: translationInstance, field: 'createdBy', 'error')} ">
	<label for="createdBy">
		<g:message code="translation.createdBy.label" default="Created By" />
		
	</label>
	<g:select id="createdBy" name="createdBy.id" from="${com.app.security.User.list()}" optionKey="id" value="${translationInstance?.createdBy?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

grails-app/views/translation/create.gsp
<!DOCTYPE html>
<%@ page import="com.app.translate.Translation" %>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translation.label', default: 'Translation')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-translation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-translation" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${translationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${translationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:translationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/translation/edit.gsp
<%@ page import="com.app.translate.Translation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translation.label', default: 'Translation')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-translation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-translation" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${translationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${translationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:translationInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${translationInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/translation/index.gsp
<%@ page import="com.app.translate.Translation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translation.label', default: 'Translation')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-translation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-translation" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="text" title="${message(code: 'translation.text.label', default: 'Text')}" />
					
						<g:sortableColumn property="translationKey" title="${message(code: 'translation.translationKey.label', default: 'Translation Key')}" />
					
						<th><g:message code="translation.language.label" default="Language" /></th>
					
						<th><g:message code="translation.updatedBy.label" default="Updated By" /></th>
					
						<th><g:message code="translation.createdBy.label" default="Created By" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${translationInstanceList}" status="i" var="translationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${translationInstance.id}">${fieldValue(bean: translationInstance, field: "text")}</g:link></td>
					
						<td>${fieldValue(bean: translationInstance, field: "translationKey")}</td>
					
						<td>${fieldValue(bean: translationInstance, field: "language")}</td>
					
						<td>${fieldValue(bean: translationInstance, field: "updatedBy")}</td>
					
						<td>${fieldValue(bean: translationInstance, field: "createdBy")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${translationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/translation/show.gsp
<%@ page import="com.app.translate.Translation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="translateMain">
		<g:set var="entityName" value="${message(code: 'translation.label', default: 'Translation')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-translation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-translation" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list translation">
			
				<g:if test="${translationInstance?.text}">
				<li class="fieldcontain">
					<span id="text-label" class="property-label"><g:message code="translation.text.label" default="Text" /></span>
					
						<span class="property-value" aria-labelledby="text-label"><g:fieldValue bean="${translationInstance}" field="text"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${translationInstance?.translationKey}">
				<li class="fieldcontain">
					<span id="translationKey-label" class="property-label"><g:message code="translation.translationKey.label" default="Translation Key" /></span>
					
						<span class="property-value" aria-labelledby="translationKey-label"><g:fieldValue bean="${translationInstance}" field="translationKey"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${translationInstance?.language}">
				<li class="fieldcontain">
					<span id="language-label" class="property-label"><g:message code="translation.language.label" default="Language" /></span>
					
						<span class="property-value" aria-labelledby="language-label"><g:link controller="language" action="show" id="${translationInstance?.language?.id}">${translationInstance?.language?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${translationInstance?.updatedBy}">
				<li class="fieldcontain">
					<span id="updatedBy-label" class="property-label"><g:message code="translation.updatedBy.label" default="Updated By" /></span>
					
						<span class="property-value" aria-labelledby="updatedBy-label"><g:link controller="user" action="show" id="${translationInstance?.updatedBy?.id}">${translationInstance?.updatedBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${translationInstance?.createdBy}">
				<li class="fieldcontain">
					<span id="createdBy-label" class="property-label"><g:message code="translation.createdBy.label" default="Created By" /></span>
					
						<span class="property-value" aria-labelledby="createdBy-label"><g:link controller="user" action="show" id="${translationInstance?.createdBy?.id}">${translationInstance?.createdBy?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:translationInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${translationInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>